import "./globals.css";
import Header from "@/components/layout/Header";
import { Saira_Condensed } from "next/font/google"

const saira = Saira_Condensed({
  subsets: ["latin"], 
  weight: ["200", "300", "400", "500", "600", "700", "800"], 
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${saira.className} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
